package org.infinispan.dataplacement.c50.keyfeature;

import java.util.Map;

/**
 * Manages the key features for all the keys generated by the application. This is application dependent, so
 * the programmer should implement this interface and pass that implementation to Infinispan
 *
 * @author Pedro Ruivo
 * @since 5.2
 */
public interface KeyFeatureManager {

   /**
    * returns an array with all the features that a key can have
    *
    * Note: this information should be static!
    *
    * @return  an array with all the features that a key can have
    */
   Feature[] getAllKeyFeatures();

   /**
    * returns the features of this particular key.
    *
    * Note: a key don't need to have all the features.
    * Note2: if you put a feature that was no returned by the method above, it will be ignored
    *
    * @param key  the key
    * @return     the features of this particular key.
    */
   Map<Feature, FeatureValue> getFeatures(Object key);

}
